server:
  port: 5000

spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=deliveryservice
    username: postgres
    password: postgres
    initialization-mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/deliveryService/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/auth/realms/deliveryService

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC

logging.level.org.springframework.security: DEBUG
